### ISSUE TITLE
Beta Testers

### ISSUE THREAD

**Issue by tjdevries** [d0c-s4vage/lookatme.contrib.image_ueberzug#1]
Let me know if / when you need a beta tester.

cc @davidbegin

**Comment by davidbegin** [comment]
Yes! I'd love to help QA

**Comment by d0c-s4vage** [comment]
Will do! I've almost got it functional, updating urwid_ueberzogen to get it to work mote robustly

**Comment by d0c-s4vage** [comment]
@davidbegin @tjdevries Thank you for offering to beta test!

I've got this in a testable state - please capture any problems/feature requests as comments on this issue or in their own issues!

Follow the instructions below (also in the [README](https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug)).

```bash
git clone https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug
cd lookatme.contrib.image_ueberzug
virtualenv /tmp/venv
. /tmp/venv/bin/activate
pip install -r requirements.txt .
lookatme example/galaxies.md
```

You should see something like the gif in the README if it works for you:

![img](https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug/raw/master/example/running.gif)

### Top concerns

* Broken, existing functionality in lookatme
  * I've had to fix problems in list rendering and table rendering that I broke while adding this feature
* Scrolling - definitely doesn't work very nicely. Images need to be cropped as they move in/out of view. Hiding the image once they're scrolled past *does* work though

**Comment by davidbegin** [comment]
Tried it out today on stream, and it worked to hilarious effect: https://www.twitch.tv/beginbot/clip/AverageAnimatedButterflyDoggo?filter=clips&range=24hr&sort=time

**Comment by d0c-s4vage** [comment]
@davidbegin Ahaha that is awesome :^) I'm hoping to get this finalized this weekend. May also create another image plugin that uses tiv https://github.com/stefanhaustein/TerminalImageViewer

**Comment by d0c-s4vage** [comment]
Turns out some changes in urwid-ueberzogen landed in the past two weeks, and I finished the updates to lookatme that let this plugin work. v1.0.0 of this plugin is out for basic, local image rendering!
